version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"  # Expose on non-default port to avoid conflict
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6378:6379"  # Expose on non-default port to avoid conflict
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
